package themekit

// studioHTML is the preview studio page. __BASE__ is replaced with the
// session's secret base path.
const studioHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Theme preview · Tringify</title>
<style>
*{box-sizing:border-box}body{margin:0;color:#171717;background:#f4f4f4;font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,select{font:inherit;color:inherit}header{background:white;border-bottom:1px solid #ddd;padding:14px 24px;display:flex;align-items:center;gap:24px;justify-content:space-between}h1{font-size:16px;line-height:1.3;margin:0;font-weight:650}.caption{color:#666;font-size:12px;margin-top:3px}.controls{display:flex;align-items:center;gap:16px;flex-wrap:wrap}label{display:flex;align-items:center;gap:8px}select{max-width:280px;min-width:160px;background:#fff;padding:8px 28px 8px 10px;border:1px solid #ccc;border-radius:6px}.devices{display:flex;border:1px solid #ccc;border-radius:6px;padding:3px;gap:3px}button{border:0;background:transparent;border-radius:3px;padding:5px 12px;cursor:pointer}button[aria-pressed=true]{background:#171717;color:white}:focus-visible{outline:2px solid #0066cc;outline-offset:3px}.status{font-size:12px;color:#555;padding:8px 24px;background:#fff;border-bottom:1px solid #ddd}.error{white-space:pre-wrap;overflow-wrap:anywhere;margin:0;padding:16px 24px;background:#fff5ed;border-bottom:1px solid #e2b18d;font:13px/1.5 ui-monospace,monospace}.canvas{height:calc(100dvh - 112px);padding:24px;display:flex;justify-content:center;align-items:stretch}iframe{width:100%;height:100%;border:1px solid #ddd;background:white;min-width:0}.canvas.mobile iframe{width:390px;max-width:100%}.empty{margin:auto;color:#555;text-align:center;padding:40px}body.has-error .canvas{height:65dvh}@media(max-width:750px){header{padding:12px 16px;align-items:flex-start;gap:12px;flex-direction:column}.controls{width:100%;gap:8px;justify-content:space-between}label{flex:1;min-width:0}select{min-width:0;width:100%;max-width:none}.caption{font-size:12px}.status{padding:8px 16px}.canvas{padding:12px;height:calc(100dvh - 160px)}button{padding:5px 10px}}
</style></head><body>
<header><div><h1 id="name">Theme preview</h1><div class="caption">Local sample data · Shopper actions are disabled</div></div><div class="controls"><label>Page <select id="pages" aria-label="Preview page"></select></label><div class="devices" aria-label="Preview width"><button type="button" data-device="desktop" aria-pressed="true">Desktop</button><button type="button" data-device="mobile" aria-pressed="false">Mobile</button></div></div></header>
<div class="status" role="status" id="status">Building your preview…</div><pre class="error" id="error" hidden></pre><main class="canvas" id="canvas"><div class="empty" id="empty">Your theme will appear here after a successful build.</div><iframe id="preview" title="Rendered theme" sandbox="allow-scripts" referrerpolicy="no-referrer" hidden></iframe></main>
<script>
const base='__BASE__',pages=document.getElementById('pages'),frame=document.getElementById('preview');let revision=-1,signature='',lastPath='';
window.addEventListener('message',event=>{if(event.source!==frame.contentWindow||event.data?.type!=='tringify-preview-page')return;const path=event.data.path;if([...pages.options].some(option=>option.value===path)){pages.value=path;lastPath=path;sessionStorage.setItem(base,path)}});
function openPage(){lastPath=pages.value;frame.src=lastPath;sessionStorage.setItem(base,lastPath)}
pages.addEventListener('change',openPage);
document.querySelectorAll('[data-device]').forEach(button=>button.addEventListener('click',()=>{document.getElementById('canvas').classList.toggle('mobile',button.dataset.device==='mobile');document.querySelectorAll('[data-device]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))}));
async function update(){try{const response=await fetch(base+'/state');if(!response.ok)throw Error();const state=await response.json();document.getElementById('name').textContent=state.name;document.getElementById('error').hidden=!state.error;document.getElementById('error').textContent=state.error;document.body.classList.toggle('has-error',!!state.error);document.getElementById('status').textContent=state.error?(state.revision?'Build failed. Showing the last successful preview.':'Fix the build error to start the preview.'):'Watching for changes · '+state.pages.length+' pages';if(state.revision!==revision&&state.pages.length){const current=pages.value||sessionStorage.getItem(base),nextSignature=JSON.stringify(state.pages);if(nextSignature!==signature){pages.replaceChildren(...state.pages.map(p=>{const o=document.createElement('option');o.value=p.path;o.textContent=p.title;return o}));if(state.pages.some(p=>p.path===current))pages.value=current;signature=nextSignature}revision=state.revision;frame.hidden=false;document.getElementById('empty').hidden=true;openPage()}}catch{document.getElementById('status').textContent='Preview disconnected. Restart the preview command to reconnect.'}finally{setTimeout(update,1000)}}update();
</script></body></html>`
